# Network Scanner Configuration
# Configurazione dello scanner di rete

scanner:
  # Subnet da scansionare
  subnets:
    - 192.168.20.0/24
    - 192.168.30.0/24
    - 192.168.40.0/24
    - 192.168.50.0/24

  # Intervallo di scansione in secondi (600 = 10 minuti)
  scan_interval: 600

  # Timeout per ogni scansione nmap in secondi
  nmap_timeout: 300

  # Database paths
  database_path: scanner/network_scan.db
  oui_database_path: scanner/oui_cache.db

  # OUI Database settings
  oui_update_days: 7
  oui_url: https://standards-oui.ieee.org/oui/oui.txt

  # Nmap settings
  nmap_arguments:
    # Scansione veloce per ping sweep
    ping_sweep: "-sn"
    # Scansione dettagliata con OS detection
    detailed_scan: "-O -sV --osscan-guess"
    # Scansione porte comuni
    port_scan: "-p 22,23,80,443,445,3389,5900,8080,8443"

  # Alert settings
  alerts:
    # Abilita alert per nuovi dispositivi
    new_device_alert: true
    # Abilita alert per dispositivi offline
    device_offline_alert: true
    # Abilita alert per cambio tipo dispositivo
    device_type_change_alert: true
    # Abilita alert per nuove porte aperte
    new_ports_alert: true

  # Performance settings
  performance:
    # Numero massimo di thread per scansione
    max_threads: 20
    # Numero massimo di host da scansionare contemporaneamente
    max_concurrent_hosts: 50
    # Delay tra scansioni host in millisecondi
    host_scan_delay: 100

  # Device detection patterns
  device_patterns:
    # Pattern personalizzati per rilevamento dispositivi
    custom:
      - name: "MikroTik Router"
        vendor_pattern: "MikroTik"
        port_pattern: [8291, 8728, 8729]
        type: "router"

      - name: "Ubiquiti AP"
        vendor_pattern: "Ubiquiti"
        port_pattern: [22, 443]
        hostname_pattern: "UAP"
        type: "ap"

      - name: "Synology NAS"
        vendor_pattern: "Synology"
        port_pattern: [5000, 5001]
        type: "nas"

  # Logging
  logging:
    # Livello di log (DEBUG, INFO, WARNING, ERROR, CRITICAL)
    level: INFO
    # Path del file di log
    file: scanner/scanner.log
    # Rotazione log (dimensione in MB)
    max_size_mb: 10
    # Numero di backup da mantenere
    backup_count: 5

  # Notifiche
  notifications:
    # Email notifications (opzionale)
    email:
      enabled: false
      smtp_server: smtp.gmail.com
      smtp_port: 587
      from_address: scanner@example.com
      to_addresses:
        - admin@example.com
      username: scanner@example.com
      password: your_password

    # Webhook notifications (opzionale)
    webhook:
      enabled: false
      url: https://your-webhook-url.com/notifications
      method: POST
      headers:
        Content-Type: application/json
        Authorization: Bearer your-token

  # Security
  security:
    # Richiede autenticazione per API
    require_auth: false
    # API key (se require_auth è true)
    api_key: your-secret-api-key
    # IP whitelist per accesso API
    ip_whitelist:
      - 127.0.0.1
      - 192.168.1.0/16